### PR TITLE
added My Recommendation section

### PR DESCRIPTION
**Pull request by Shani-08**
This bring the recommended videos using Activities call, it shows
Recommended and Upload kinds. No Translation done.

### CODE REVIEW

**Comment by bromix** [comment]
Activities do not resemble recommendations. In a worse car your result will be empty.

**Comment by Shani-08** [comment]
Yes i realized that but checking for Recommended we well Upload type, we can bring those videos, alteast with my test it looked better. We can add more types to check as well.
I dont think there is any api for  Recomemeded section in v3.

**Comment by bromix** [comment]
Correct...YouTube/Google dropped the support for recommended videos and channels. Another problem with the activities was duplicate videos, because the same video was lived, uploaded or commented. The whole activities stream is not usefully for a list of videos.

**Comment by Shani-08** [comment]
Thanks. Do you think a better idea would be to fetch few pages till we get 30 recommended videos? We can check if it's recommended video type, currently I am only checking upload and recommended so there are no duplicate as far as I can see.

**Pull request closed without merging**
