### PR TITLE
master

### PR DESCRIPTION
**Pull request by tcatut**

### CODE REVIEW

**Comment by bromix** [comment]
First up...nice coding...first PR I see with a clean code :)

But here is the problem with the Activities (btw...where are the recommendations? ;) )
I have duplicate and incomplete video items mixed with playlists and channel items...what is what....the usability is totally broken and that's why I haven't implemented the activities for the addon (again)...in an early alpha version August 2014 (https://github.com/bromix/plugin.video.youtube/commit/262bda1370035bc5cda73adaafaf870ffb2d0e52) I already used the activities and removed them, because no one would understand the result...including me :)

Here is an example what it looks like based on my subscriptions:
Duplicate and incomplete video items

**Comment by bromix** [comment]
The Activities are the new Feed starting with APIv3...it's the replacement for **My Subscriptions** and will be deprecated in May 2015. The Activities are based on your subscriptions (channels). It includes (you already noticed) everything a user/channel is doing...so we have to come up with a solution to show it to the user so he can understand it and not pollute the list just with content.
The user needs some kind of feedback/information which will state, that the result is a **like** of a user/channel, or he just **uploaded** a video...and so on...but I don't know how...I appreciate your time and work...but we have to do it better. This will come back like a boomerang.

**Comment by bromix** [comment]
Also a hint :) if you make changes to a project...always create a new branch of it.

**1.** fork Project
**2.** create a new branch
**3.** make changes
**4.** commit to your branch
**5.** create PR from that branch

**Comment by tcatut** [comment]
Yeah, I was having some of the same thoughts as I wrote it.  I wanted to get basic functionality going before getting further.  Let me look at it a bit and see if I can come with some ideas.

**Pull request closed without merging**
