### PR TITLE
frodo fix, again :)))

### PR DESCRIPTION
**Pull request by weekendsource**
jarvis fix broke poor frodo

### CODE REVIEW

**Comment by weekendsource** [comment]
frodo is missing some methods, ie SORT_METHOD_CHANNEL etc (http://mirrors.xbmc.org/docs/python-docs/12.2-frodo/xbmcplugin.html vs http://mirrors.xbmc.org/docs/python-docs/15.x-isengard/xbmcplugin.html), so can we default missing methods to 0 (SORT_METHOD_NONE)?

**Comment by guidosarducci** [comment]
Just some background and my 2 cents...

Actually, the code for Frodo (and Gotham -> Jarvis) was broken before, since it used fixed values for sort method constants but the constants change between versions.  It just wasn't noticed before and the "Jarvis fix" exposed it.  When I did that commit, I only checked back to Gotham while investigating because I didn't know anyone still uses Frodo :).  But looking at the Changelog and Forum, I see Frodo is supposed to be supported.

Generating fake sort method constants made sense for testing but I think is a bad idea when running inside Kodi as in your patch.  It could have unintended side-effects, which could also change between versions. Also, if an author explicitly uses a sort method from `const_sort_methods.py` they expect it to work, but this patch just hides any error and makes it difficult to troubleshoot.

The problem for Frodo is that Gotham added 8 new sort method constants, and the constants in `const_sort_methods.py` look to be based on Gotham/Helix/Isengard.

If Frodo is supported, I think a better approach is to remove those 8 constants introduced by Gotham. I don't believe they've been used before and doubt they will be in the future.  I attached an example patch that removes them.

A couple of points for reference...  I'm only aware of the addon using a few sort methods:
````
LABEL_IGNORE_THE
UNSORTED
VIDEO_RUNTIME
VIDEO_TITLE
VIDEO_YEAR
DATE
````

The sort methods removed by the attached patch are below, and don't seem too relevant to Youtube. Not sure if 'DATEADDED' could be a problem, but we already have 'DATE'.
````
SORT_METHOD_CHANNEL
SORT_METHOD_COUNTRY
SORT_METHOD_DATEADDED
SORT_METHOD_DATE_TAKEN
SORT_METHOD_FULLPATH
SORT_METHOD_LABEL_IGNORE_FOLDERS
SORT_METHOD_LASTPLAYED
SORT_METHOD_PLAYCOUNT
````

Note also that Jarvis added `SORT_METHOD_VIDEO_USER_RATING`, but I didn't add that to the "Jarvis fix" commit for similar reason as above.

In any case, it's **bromix's** call so let's see what they think...

[youtube-frodo-patch.txt](https://github.com/bromix/plugin.video.youtube/files/46980/youtube-frodo-patch.txt)

**Comment by bromix** [comment]
@guidosarducci thanks for the update...can you point me to the KODI sources where I can find the current constants for the sort methods?

I've to think about the Frodo patch :) Frodo is really old now a days....a backward compatibility means always more work on my end in the future....it's like using still Windows XP ;)

**Comment by Razzeee** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/SortFileItem.h

**Comment by guidosarducci** [comment]
FYI, I did my comparisons starting here: http://mirrors.xbmc.org/docs/python-docs/,
and the Pythonic xbmcplugin constants are at the bottom here: http://mirrors.xbmc.org/docs/python-docs/16.x-jarvis/xbmcplugin.html.

@bromix Yeah, that's why I only looked back to Gotham to fix sorting, but was then surprised to find Frodo support in the code!

**Comment by weekendsource** [comment]
sapienti sat :)))) well, if the progress demands to get rid of the old hardware, so be it. 

I just thought that it would be nice to retain compatibility with frodo, because there is a number of boxes and sticks with frodo installed in non-technical users homes :)

**Comment by weekendsource** [comment]
I'm really not an expert, just my two cents on the xbmc/kodi constants problem. New constants were not added on the bottom of the declaration in https://github.com/xbmc/xbmc/blob/master/xbmc/SortFileItem.h and like, but instead they were added like this:
 
https://github.com/xbmc/xbmc/commit/0e0dbde0330d77ca1d48d378cb6b3f88a64dd72c#diff-6b3ab0e868ac40c42492973413aafb4f

https://github.com/xbmc/xbmc/commit/e9fd428ed3ee339d3db980a884cb7dc144a64094#diff-6b3ab0e868ac40c42492973413aafb4f etc...

Maybe adding at the bottom would made kodi source look uglier ;) but it would save many addons from running into compatibility problems.

**Comment by MartijnKaijser** [comment]
You should never use constant but the sort name

**Comment by MartijnKaijser** [comment]
Additionally, die Frodo die

**Comment by bjacog** [comment]
Thank you @guidosarducci I commented those sort methods out and it worked like a boss.

**Comment by exxerion** [comment]
I agree with everyone that it should be fixed as Frodo is still very widely used. And you will ask: Why?

Actually there's a lot of hardware out there that only support Frodo (by one reason or another), like Apple TV mark1, some Android Boxes, M8, MX2, etc. And not everybody can upgrade or just scrap everything and get new hardware.

In my case, I have Frodo on a Nvidia Ion2 box with OpenElec. And that's the most convenient way to keep it. Why? Because as soon as I upgrade it loses a lot of good things. The most important one is that as soon I upgrade it, it loses the ability of playing HD content with Lanczos3 without a single frame drop. Later xbmcs/kodis can't do that in that setup (and believe me I know what I am telling as I am a techie, and I got a lot of headaches with custom builds).

The plugin is flawless up to this revision: plugin.video.youtube-845eb33b01db2865a9272f2954602f703c7f8cb0

And surprisingly most of the plugins out there are still compatible with Frodo.

As xbmc/kodi user, I have the feeling that Kodi is moving forward fast (maybe way too fast) and is losing some good things on the way, but well, just my opinion.

A happy Frodo user.

**Comment by guidosarducci** [comment]
@bromix I don't believe this is really a Frodo issue after all... Thinking about this a little more, the main purpose of `const_sort_methods.py` is to provide abstraction for the test framework, and not to unnecessarily duplicate **all** the sort constants from `xbmcplugins`.  Since the addon actually uses only a few constants, it might be cleaner and more maintainable to remove any constants that aren't currently used.  If you want to use different sorting in the future, you can add them to `const_sort_methods.py` at that time, as well as deciding on version compatibility.

A side effect of making this change would be that the addon continues to work on all Kodi versions, including of course Frodo. :)

**Comment by weekendsource** [comment]
Still open? FRODO: Mein Sorgenkind ;)

**Comment by bromix** [comment]
See https://github.com/bromix/plugin.video.youtube/commit/2f37193e7eb290930b9ba5d82bd926a28f720d24

**Pull request closed without merging**
