### PR TITLE
[fix] Don't hardcode sort method enums because they may change between Kodi versions

### PR DESCRIPTION
**Pull request by guidosarducci**
Hi bromix,
This is a fix for an annoying problem I ran into testing Isengard -> Jarvis migration, where video sorting under Jarvis is messed up. Root cause is that xbmcplugin module constants are hardcoded in the addon, but changed between Isengard and Jarvis. I've confirmed this update works on both Isengard and Jarvis.

Please have a look and thanks for all your work on this addon.

### CODE REVIEW

**Comment by bromix** [comment]
This is an abstract implementation. Your fix will break the mockup for tests. Sorting in Jarvis is broken, not the other way around.

**Comment by bromix** [comment]
Can you create something with an try import around the xbmcplugin import and for failing we use my "hardcoded" constants. Then your fix would work.

**Comment by guidosarducci** [comment]
I haven't really looked into your test framework. Are the previous constants being tested against reference values, or can they be arbitrary? Assuming the latter case, would this latest commit work for testing, which just uses sequential dummy values if no xbmc present?

Can you elaborate when you say "sorting in Jarvis is broken"? More than enums changing?

**Comment by bromix** [comment]
Awesome...that's it...thank you very much :) you're one of only a few people who helped me a lot with a PR ;)
Sorry for first closing the issue, I saw afterwards my error with the constants. I've never found the bug in Jarvis.

**Comment by guidosarducci** [comment]
You are very welcome and I'm glad to help considering how much we use the addon but take it for granted often! I admit I was a lttle confused when you closed the PR but not problem. Take care.

**Pull request merged**
